services:
  - type: web
    name: inkwell-notes
    runtime: python
    buildCommand: chmod +x render_build.sh && ./render_build.sh
    startCommand: cd backend && gunicorn notesapp_config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "*"
